---
  SIGNAL:
    default_channel_sequence:
      - I
      - II
      - III
      - AVR
      - AVL
      - AVF
      - V1
      - V2
      - V3
      - V4
      - V5
      - V6
    default_fs: 250
  WAVES:
    qrs_duration_min: 0.02
    qrs_duration_max: 0.2
    qrs_ventricular_min: 0.12
  QT:                   # Анализ QT
    histogram_bins: 10  # Число интервалов для построения гистограммы распределения
    3sigma: False       # Цензурирование гистограммы по правилу трех сигм
  STT:                  # Анализ ST-T
    kodama_elev_t: 0.1  # Пороговое значение элевации Kodama (мВ)
    kodama_depr_t: 0.1  # Пороговое значение депрессии Kodama (мВ)
    kodama_elev_dur: 0.08  # Длительность элевации Kodama (сек)
    k1_duration: 0.06     # Длительность эпизода депрессии Kodama-1 (сек)
    kodama_relation: 1.4  # Порог отношения смещения st к ЧСС Kodama
                             # [мВ/уд/мин]
    ellestad_depr_t1: 0.2  # Пороговое значение косонисходящей
                           # депрессии Ellestad (мВ)
    ellestad_depr_t2: 0.1  # Пороговое значение косовосходящей
                           # депрессии Ellestad (мВ)
    ellestad_duration: 0.08 # длительность депрессии Ellestad (сек)
    min_episode: 5          # минимальное число циклов для создания эпизода
  RHYTHM:
    min_episode: 5          # минимальное число циклов для создания эпизода
    norm_bpm_min: 60        # минимальная ЧСС нормального синусового ритма
    norm_bpm_max: 100       # максимальная ЧСС нормального синусового ритма
  BLOCK:
    mobitz_pq: 0.2          # пороговое значение PQ-интервала для обнаружения AV-блокады
    min_pause: 1.5          # минимальная длительность паузы относительно ожидаемой длительности RR
  RSVAR:
    sampling: 1.0           # частота дискретизации ритма, Гц
    freq_bands:             # границы частотных диапазонов, от 0.0 до 0.5*sampling
    - 0.0
    - 0.003
    - 0.04
    - 0.15
    - 0.4