---
  PREPROCESSING:
    baseline_correction: true
    mains_correction: true

  BASELINE:
    unbias_window_ms: 1500

  MAINS_FILTER:
    base_freq: 50
    attenuation: 0.05
    fft_size: 512

  BATCH_PROCESSING:
    output_file_suffix: _F