---
  PREPROCESSING:
    baseline_correction: true
    mains_correction: true

  BASELINE:
    unbias_window_ms: 1500

  MAINS_FILTER:
    base_freq: 50
    attenuation: 0.05
    fft_size: 512

  SEGMENTATION:
    min_qrs_ms: 20
    min_st_ms: 80
    j_offset_ms: 60

  BATCH_PROCESSING:
    output_file_suffix: _F